# Generated by Django 3.2.6 on 2021-09-16 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='jobList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_Title', models.CharField(max_length=255, verbose_name='Job Title')),
                ('job_Description', models.TextField(max_length=255, verbose_name='Job Description')),
                ('is_onHire', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Job List',
            },
        ),
        migrations.CreateModel(
            name='jobSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=255, verbose_name='Job Skill')),
                ('job_Title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.joblist')),
            ],
            options={
                'verbose_name': 'Job Skill List',
            },
        ),
    ]
