# Generated by Django 3.2.7 on 2021-09-25 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_manpower_lastsubmitted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manpower',
            name='expectedDate',
        ),
    ]
