# Generated by Django 3.2.7 on 2021-09-26 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0006_manpower_is_finished'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manpower',
            name='designation',
        ),
    ]
