# Generated by Django 3.2.7 on 2021-09-28 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0007_remove_manpower_designation'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('subject', models.CharField(max_length=255, verbose_name='Subject')),
                ('message', models.TextField(max_length=500, null=True, verbose_name='Message')),
            ],
        ),
    ]
