# Generated by Django 3.2.7 on 2021-09-28 02:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0008_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='lastSubmitted',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date Submmited'),
            preserve_default=False,
        ),
    ]
