# Generated by Django 3.2.7 on 2021-09-29 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0009_contact_lastsubmitted'),
    ]

    operations = [
        migrations.AddField(
            model_name='manpower',
            name='on_Going',
            field=models.BooleanField(default=False),
        ),
    ]
