# Generated by Django 3.2.7 on 2021-09-29 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0010_manpower_on_going'),
    ]

    operations = [
        migrations.AddField(
            model_name='manpower',
            name='job_Title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='system.joblist'),
        ),
        migrations.AlterField(
            model_name='joblist',
            name='job_Title',
            field=models.CharField(max_length=255, unique=True, verbose_name='Job Title'),
        ),
    ]
