# Generated by Django 3.2.7 on 2021-10-06 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0012_auto_20210929_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='manpower',
            name='email',
            field=models.CharField(blank=True, max_length=255, verbose_name='Requester Email'),
        ),
    ]
