# Generated by Django 3.2.6 on 2021-09-04 15:30

import clientApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldetails',
            name='profile_image',
            field=models.ImageField(blank=True, default=clientApp.models.get_default_profile, max_length=255, null=True, upload_to=clientApp.models.get_profile_image_filepath),
        ),
    ]
