# Generated by Django 3.2.6 on 2021-09-06 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientApp', '0002_rename_personal_employmenthistory_personaldetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='accounts',
        ),
        migrations.RemoveField(
            model_name='link',
            name='accounts',
        ),
        migrations.RemoveField(
            model_name='reference',
            name='accounts',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='accounts',
        ),
        migrations.AddField(
            model_name='education',
            name='personaldetails',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clientApp.personaldetails'),
        ),
        migrations.AddField(
            model_name='link',
            name='personaldetails',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clientApp.personaldetails'),
        ),
        migrations.AddField(
            model_name='reference',
            name='personaldetails',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clientApp.personaldetails'),
        ),
        migrations.AddField(
            model_name='skill',
            name='personaldetails',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clientApp.personaldetails'),
        ),
    ]
