# Generated by Django 3.2.6 on 2021-09-06 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientApp', '0004_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='headline',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
