# Generated by Django 3.2.6 on 2021-09-06 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientApp', '0007_rename_account_article_accounts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='accounts',
            new_name='account',
        ),
    ]
