# Generated by Django 3.2.6 on 2021-09-10 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientApp', '0013_auto_20210910_1744'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personaldetails',
            options={'verbose_name': 'Personal Detail'},
        ),
    ]
