# Generated by Django 3.2.6 on 2021-09-14 05:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clientApp', '0014_alter_personaldetails_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='dateSubmit',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date Submit'),
            preserve_default=False,
        ),
    ]
