# Generated by Django 3.2.6 on 2021-09-15 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientApp', '0016_auto_20210915_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='jobTitle',
            field=models.CharField(blank=True, choices=[('Copy Writer', 'Copy Writer'), ('Translator', 'Translator'), ('Editor', 'Editor'), ('None', 'None')], default='None', max_length=50, null=True, verbose_name='Job Title'),
        ),
    ]
