# Generated by Django 3.2.6 on 2021-09-15 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientApp', '0018_auto_20210915_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='dateSubmit',
            field=models.DateTimeField(auto_now=True, verbose_name='Date Submit'),
        ),
    ]
