# Generated by Django 3.2.6 on 2021-09-20 04:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientApp', '0021_jobapplication_is_validated'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='article',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Article Score'),
        ),
    ]
