# Generated by Django 3.2.6 on 2021-09-20 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientApp', '0023_jobapplication_overall'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='overall',
        ),
    ]
