# Generated by Django 3.2.6 on 2021-09-20 05:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientApp', '0024_remove_jobapplication_overall'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='copywriterfinal',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Copywriter Score'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='editorfinal',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Editor Score'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='translatorfinal',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Translator Score'),
        ),
    ]
