# Generated by Django 3.2.6 on 2021-09-20 11:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientApp', '0025_auto_20210920_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='copywriterfinal',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Copywriter FS'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='editorfinal',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Editor FS'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='translatorfinal',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Translator FS'),
        ),
    ]
