# Generated by Django 3.2.6 on 2021-09-20 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientApp', '0026_auto_20210920_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='remarks',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
