# Generated by Django 3.2.6 on 2021-09-20 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientApp', '0028_jobapplication_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='is_copywriter_hired',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='is_editor_hired',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='is_translator_hired',
            field=models.BooleanField(default=False),
        ),
    ]
