# Generated by Django 3.2.6 on 2021-09-20 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientApp', '0029_auto_20210920_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='jobAccepted',
            field=models.CharField(blank=True, default='None', max_length=255, null=True),
        ),
    ]
