# Generated by Django 3.2.6 on 2021-09-21 09:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clientApp', '0030_jobapplication_jobaccepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='dateAccepted',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Submit'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='jobAccepted',
            field=models.CharField(blank=True, default='None', max_length=255, null=True, verbose_name='Accepted Job'),
        ),
    ]
