# Generated by Django 3.2.6 on 2021-09-21 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientApp', '0031_auto_20210921_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='dateAccepted',
            field=models.DateTimeField(null=True, verbose_name='Date Submit'),
        ),
    ]
