# Generated by Django 3.2.6 on 2021-09-21 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientApp', '0032_alter_jobapplication_dateaccepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='dateAccepted',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='jobAccepted',
            field=models.CharField(default='None', max_length=255, null=True, verbose_name='Accepted Job'),
        ),
    ]
