# Generated by Django 3.2.6 on 2021-09-21 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientApp', '0033_auto_20210921_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='jobAccepted',
            field=models.CharField(blank=True, default='None', max_length=255, null=True, verbose_name='Accepted Job'),
        ),
    ]
