# Generated by Django 3.2.7 on 2021-09-24 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientApp', '0034_alter_jobapplication_jobaccepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='remarks',
            field=models.TextField(blank=True, default='Writeam Staff are reviewing your resume and article', max_length=255, null=True),
        ),
    ]
