# Generated by Django 3.2.6 on 2021-09-25 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientApp', '0035_alter_jobapplication_remarks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='is_copywriter_hired',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='is_editor_hired',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='is_translator_hired',
        ),
    ]
