# Generated by Django 3.2.7 on 2021-09-26 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientApp', '0036_auto_20210925_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='validationDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
