# Generated by Django 3.2.7 on 2021-09-27 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientApp', '0037_jobapplication_validationdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='dateSubmit',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date Submit'),
        ),
    ]
