# Generated by Django 3.2.7 on 2021-09-30 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientApp', '0038_alter_jobapplication_datesubmit'),
    ]

    operations = [
        migrations.CreateModel(
            name='deploymentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('password', models.CharField(blank=True, max_length=30, null=True)),
                ('is_gcash', models.BooleanField(default=False)),
                ('gname', models.CharField(blank=True, max_length=255, null=True)),
                ('gnumber', models.CharField(blank=True, max_length=255, null=True)),
                ('is_bank', models.BooleanField(default=False)),
                ('bname', models.CharField(blank=True, max_length=255, null=True)),
                ('bnumber', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Deployment',
            },
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='remarks',
            field=models.TextField(blank=True, default='Please wait for the HR to view your application', max_length=255, null=True),
        ),
    ]
