# Generated by Django 3.2.7 on 2021-09-30 06:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clientApp', '0039_auto_20210930_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='deploymentmodel',
            name='accounts',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
