# Generated by Django 3.2.7 on 2021-10-06 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientApp', '0042_alter_personaldetails_nationality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldetails',
            name='profSummary',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
