# Generated by Django 3.2.6 on 2021-09-03 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_accounts_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='phone'),
        ),
    ]
