# Generated by Django 3.2.6 on 2021-09-15 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_accounts_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
