# Generated by Django 3.2.6 on 2021-10-03 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_accounts_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='address',
            field=models.TextField(blank=True, max_length=50, null=True, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='phone'),
        ),
    ]
