# Generated by Django 3.2.6 on 2021-09-30 11:28

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='onboardingApplicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobTitle', models.CharField(blank=True, choices=[('Copy Writer', 'Copy Writer'), ('Translator', 'Translator'), ('Editor', 'Editor'), ('None', 'None')], default='None', max_length=50, null=True, verbose_name='Job Title Accepted')),
                ('score', models.PositiveIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Applicant Score')),
                ('status', models.CharField(blank=True, choices=[('NONE', 'NONE'), ('FAILED', 'FAILED'), ('PASSED', 'PASSED')], default='NONE', max_length=30, null=True)),
                ('dateScore', models.DateTimeField(auto_now_add=True, verbose_name='Date Validate')),
                ('remarks', models.TextField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('accounts', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Onboarding Applicant',
            },
        ),
    ]
