# Generated by Django 3.2.6 on 2021-09-10 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboardingapplicant',
            name='remarks',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='onboardingapplicant',
            name='jobTitle',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Job Title Accepted'),
        ),
    ]
