# Generated by Django 3.2.6 on 2021-09-10 09:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0002_auto_20210910_1746'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='onboardingapplicant',
            options={'verbose_name': 'Onboarding Applicants'},
        ),
        migrations.AddField(
            model_name='onboardingapplicant',
            name='dateScore',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date Validate'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='onboardingapplicant',
            name='last_login',
            field=models.DateTimeField(auto_now=True, verbose_name='last_login'),
        ),
        migrations.AddField(
            model_name='onboardingapplicant',
            name='status',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
