# Generated by Django 3.2.6 on 2021-09-10 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0004_auto_20210910_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onboardingapplicant',
            name='jobTitle',
            field=models.CharField(blank=True, choices=[('Copy Writer', 'Copy Writer'), ('Translator', 'Translator'), ('Editor', 'Editor')], default='Copy Writer', max_length=50, null=True, verbose_name='Job Title Accepted'),
        ),
        migrations.AlterField(
            model_name='onboardingapplicant',
            name='status',
            field=models.CharField(blank=True, choices=[('FAILED', 'FAILED'), ('PASSED', 'PASSED')], default='FAILED', max_length=30, null=True),
        ),
    ]
