# Generated by Django 3.2.6 on 2021-09-10 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0005_auto_20210910_1756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onboardingapplicant',
            name='last_login',
        ),
        migrations.AlterField(
            model_name='onboardingapplicant',
            name='jobTitle',
            field=models.CharField(blank=True, choices=[('Copy Writer', 'Copy Writer'), ('Translator', 'Translator'), ('Editor', 'Editor'), ('None', 'None')], default='None', max_length=50, null=True, verbose_name='Job Title Accepted'),
        ),
    ]
